
CREATE TABLE P1 (
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	tempurature DEC(5,2),
	PRIMARY KEY (ts)
);

CREATE TABLE P2 (
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	tempurature DEC(5,2),
	PRIMARY KEY (ts)
);