
CREATE TABLE TEMPERATURE_HISTORY (
	EFFDT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DEVICE_ID INT,
	temperature DEC(5,2),
	PRIMARY KEY (EFFDT)
);

CREATE TABLE CURRENT_TEMPERATURE (
	EFFDT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DEVICE_ID INT,
	temperature DEC(5,2),
	PRIMARY KEY (EFFDT)
);